version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BASE_URL = http://api.weatherapi.com/v1
      - REACT_APP_SERVER_URL = your_server_url/api/v1
      - REACT_APP_API_KEY = your_weatherapi_key
    volumes:
      - .:/app
      - /app/node_modules
