version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BASE_URL = http://api.weatherapi.com/v1
      - REACT_APP_SERVER_URL = http://localhost:8000/api/v1
      - REACT_APP_API_KEY = 58589eee37c44124a95111145240108
    volumes:
      - .:/app
      - /app/node_modules
